default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: product_api_development

test:
  <<: *default
  database: product_api_test

production:
  primary:
    <<: *default
    url: postgresql://rubyswag_db_user:MrTecGetGxTV2cezdCSh0JVaFidd9JcE@dpg-daj7hm7qj5pc73chf7qg-a/rubyswag_db